# Generated by Django 3.1.7 on 2021-04-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_code', models.CharField(blank=True, max_length=255, null=True)),
                ('area_deep', models.IntegerField(blank=True, null=True)),
                ('area_name', models.CharField(blank=True, max_length=30, null=True)),
                ('area_parent_id', models.IntegerField(blank=True, null=True)),
                ('area_region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=30)),
                ('aphone', models.CharField(max_length=11)),
                ('addr', models.CharField(max_length=100)),
                ('isdefault', models.BooleanField(default=False)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.userinfo')),
            ],
        ),
    ]
