# Generated by Django 3.1.7 on 2021-04-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='corlorid',
            new_name='colorid',
        ),
    ]
